### PR TITLE
Update directory to point to main rinkeby deployment

### PR DESCRIPTION
**Pull request by clamdad**
This PR updates the telliot-core to point to the final rinkeby deployed addresses and ABIs.

@tallywiesenberg @themandalore 

Please verify/update the following ABIs contents

- [ ] https://github.com/tellor-io/telliot-core/blob/directory-updates/src/telliot_core/directory/_tellorx/master_abi.json
- [ ] https://github.com/tellor-io/telliot-core/blob/directory-updates/src/telliot_core/directory/_tellorx/oracle_abi.json
- [ ] https://github.com/tellor-io/telliot-core/blob/directory-updates/src/telliot_core/directory/_tellorx/governance_abi.json
- [ ] https://github.com/tellor-io/telliot-core/blob/directory-updates/src/telliot_core/directory/_tellorx/treasury_abi.json

### CODE REVIEW

**Comment by clamdad** [comment]
Closes #143

**Comment by tallywiesenberg** [comment]
the master ABI linked here doesn't include the controller or token functionality

**Comment by clamdad** [comment]
> the master ABI linked here doesn't include the controller or token functionality

@tallywiesenberg That's what I was afraid of.  Can you please update any ABI files in prep for Rinkeby tomorrow?

**Review by tallywiesenberg — APPROVED** [review]
I have updated the ABIs. I concatenated the controller abi to the master abi.

**Comment by clamdad** [comment]
@tallywiesenberg We can't fully test this until rinkeby is deployed, but the CI tests seem to fail with a suspicious error:
```
 E           ValueError: Abi contains functions with colliding selectors. Functions _allowances(address,address), _allowances(address,address) have selector 0x024c2ddd and
  E           addresses(bytes32), addresses(bytes32) have selector 0x699f200f and
  E           balances(address,uint256), balances(address,uint256) have selector 0xcbf1304d and
  E           bytesVars(bytes32), bytesVars(bytes32) have selector 0x62dd1d2a and
  E           currentMiners(uint256), currentMiners(uint256) have selector 0x1fd22364 and
  E           disputeIdByDisputeHash(bytes32), disputeIdByDisputeHash(bytes32) have selector 0xd01f4d9e and
  E           disputesById(uint256), disputesById(uint256) have selector 0xdb085beb and
  E           migrated(address), migrated(address) have selector 0x4ba0a5ee and
  E           minersByChallenge(bytes32,address), minersByChallenge(bytes32,address) have selector 0x48b18e54 and
  E           newValueTimestamps(uint256), newValueTimestamps(uint256) have selector 0x438c0aa3 and
  E           requestIdByQueryHash(bytes32), requestIdByQueryHash(bytes32) have selector 0x5700242c and
  E           uints(bytes32), uints(bytes32) have selector 0xb59e14d4
```

**Comment by tallywiesenberg** [comment]
> @tallywiesenberg We can't fully test this until rinkeby is deployed, but the CI tests seem to fail with a suspicious error:
> 
> ```
>  E           ValueError: Abi contains functions with colliding selectors. Functions _allowances(address,address), _allowances(address,address) have selector 0x024c2ddd and
>   E           addresses(bytes32), addresses(bytes32) have selector 0x699f200f and
>   E           balances(address,uint256), balances(address,uint256) have selector 0xcbf1304d and
>   E           bytesVars(bytes32), bytesVars(bytes32) have selector 0x62dd1d2a and
>   E           currentMiners(uint256), currentMiners(uint256) have selector 0x1fd22364 and
>   E           disputeIdByDisputeHash(bytes32), disputeIdByDisputeHash(bytes32) have selector 0xd01f4d9e and
>   E           disputesById(uint256), disputesById(uint256) have selector 0xdb085beb and
>   E           migrated(address), migrated(address) have selector 0x4ba0a5ee and
>   E           minersByChallenge(bytes32,address), minersByChallenge(bytes32,address) have selector 0x48b18e54 and
>   E           newValueTimestamps(uint256), newValueTimestamps(uint256) have selector 0x438c0aa3 and
>   E           requestIdByQueryHash(bytes32), requestIdByQueryHash(bytes32) have selector 0x5700242c and
>   E           uints(bytes32), uints(bytes32) have selector 0xb59e14d4
> ```

good catch. this means there are duplicates inside the ABI

**Comment by clamdad** [comment]
I could use some help with this one.  Web3.py is rejecting the combined ABI file.

**Pull request merged**
