### PR TITLE
Feat: Add fuse network configuration

### PR DESCRIPTION
**Pull request by t0mcr8se**
~ Add the fuse network info in endpoints.py
~ Add TellorFlex and wFUSE contract addresses in contract_directory.json

### CODE REVIEW

**Comment by clamdad** [comment]
Note that the endpoints in `endpoints.py` are only used as defaults for initial creation of the user's `endpoints.yaml` file.  Therefore, if a user already has an `endpoints.yaml` file, the fuse endpoint will need to be manually added to it.

**Comment by clamdad** [comment]
Current users are accustomed to managing their own endpoints through the endpoints.yaml file, so probably don't need to do anything.

**Review by oraclown — APPROVED** [review]
Looks great!

**Comment by oraclown** [comment]
Closing to continue [here](https://github.com/tellor-io/telliot-core/pull/227)

**Pull request closed without merging**
